// Applied Tech site — all course/teacher/pathway content lives here.
// Edit this file to change what appears on the site. No build step.
// Schema is documented in README.md.

window.DATA = {
  teachers: {
    ak: {
      id: "ak",
      initials: "AK",
      name: "Adam Kirsch",
      site: "cvhs",
      focus: "Engineering",
      bio: "Engineering teacher at CVHS. Leads Intro to Engineering and Engineering Science; also teaches in the Woods and Architecture lanes.",
    },
    am: {
      id: "am",
      initials: "AM",
      name: "Andy McAteer",
      site: "cvhs",
      focus: "Industrial Design",
      bio: "Industrial design teacher at CVHS. Leads the Industrial Design pathway and contributes to Intro to Engineering and the freshman shop row.",
    },
    rm: {
      id: "rm",
      initials: "RM",
      name: "Randy Macdonald",
      site: "chs",
      focus: "Computer Science",
      bio: "Computer science teacher at CHS. Leads the CS ladder from Computer Skills through Capstone CS; co-listed on Industrial Design.",
    },
    sr: {
      id: "sr",
      initials: "SR",
      name: "Stephanie Reinwald",
      site: "cvhs",
      focus: "Architecture",
      bio: "Architecture teacher. Leads Architecture and co-teaches Intro to Engineering and the freshman shop row.",
    },
    jj: {
      id: "jj",
      initials: "JJ",
      name: "JJ Keim",
      site: "chs",
      focus: "Advanced Metals & Automotive",
      bio: "Metals and automotive teacher at CHS. Leads the Autos ladder, Metals II, Vehicular/Drone Design, and co-teaches Engineering Science and Real World Math.",
    },
  },

  pathways: {
    cs: {
      id: "cs",
      title: "Computer Science",
      color: "#3b82f6",
      site: "chs",
      type: "ladder",
      description:
        "A three-year sequence at CHS that moves from foundational programming to a year-long capstone project. Each course builds directly on the one before it.",
      entry: ["computer-skills"],
      courses: ["intro-to-cs", "advanced-cs", "capstone-cs"],
      capstone: "capstone-cs",
    },
    engineering: {
      id: "engineering",
      title: "Engineering",
      color: "#10b981",
      site: "cvhs",
      type: "collection",
      description:
        "Year-long engineering courses at CVHS. Intro to Engineering teaches the design process and CAD; Engineering Science is the dual-credit (CTE + science) physics-and-design course. Take either, both, or neither — they don't require each other.",
      entry: ["woods-1", "metals-1"],
      courses: ["intro-to-engineering", "engineering-science"],
    },
    architecture: {
      id: "architecture",
      title: "Architecture",
      color: "#f59e0b",
      site: "cvhs",
      type: "collection",
      description:
        "Residential and light commercial design using Revit and Arduino-based microcontrollers. Students move from hand sketches to full building models and integrate simple smart-building electronics.",
      entry: ["woods-1"],
      courses: ["architecture"],
    },
    woods: {
      id: "woods",
      title: "Woods & Carpentry",
      color: "#b45309",
      site: "cvhs",
      type: "collection",
      description:
        "Two distinct year-long courses at CVHS. Woods II goes deep on furniture-grade joinery, finish, and CNC work. Carpentry is the construction course — it runs the Unity Shelter tiny-home build. They're peers, not a ladder: a student can take either one after Woods 1, or both.",
      entry: ["woods-1"],
      courses: ["woods-2", "carpentry"],
    },
    metals: {
      id: "metals",
      title: "Metals",
      color: "#6b7280",
      site: "chs",
      type: "ladder",
      description:
        "A two-year advanced metals sequence at CHS. Metals II builds the welding and machining foundation (MIG, oxy-acetylene, arc, basic machining). Metals III extends into AWS SENSE Level 1 welding with TIG added for thin-gauge steel and aluminum, plus a documented capstone fabrication. Metals 1 (freshman row) is the entry.",
      entry: ["metals-1"],
      courses: ["metals-2", "metals-3"],
    },
    autos: {
      id: "autos",
      title: "Automotive",
      color: "#dc2626",
      site: "chs",
      type: "ladder",
      description:
        "A three-year hands-on automotive sequence at CHS covering operation, diagnosis, construction, and repair of cars and light trucks. Each course builds on the diagnostics and shop skills of the one before it.",
      entry: ["metals-1"],
      courses: ["autos-1", "autos-2", "autos-3"],
    },
    "industrial-design": {
      id: "industrial-design",
      title: "Industrial Design",
      color: "#8b5cf6",
      site: "cvhs",
      type: "ladder",
      description:
        "Product design, mechanical engineering concepts, and digital-to-physical manufacturing. Industrial Design I builds the CAD and prototyping skills that Industrial Design II's self-directed project depends on.",
      entry: ["woods-1", "metals-1"],
      courses: ["industrial-design", "industrial-design-2"],
    },
    vehicular: {
      id: "vehicular",
      title: "Vehicular / Drone Design",
      color: "#ec4899",
      site: "chs",
      type: "collection",
      description:
        "A capstone-style course at CHS where students design, build, and test a vehicle or drone from the ground up. Draws on metals, electronics, and project-management skills from across Applied Tech.",
      entry: ["metals-1"],
      courses: ["vehicular-drone-design"],
    },
    math: {
      id: "math",
      title: "Real World Math",
      color: "#0ea5c4",
      site: "cvhs",
      type: "collection",
      description:
        "A standalone math-credit course anchored in shop and industry applications — measurement, layout, trig for trades, estimation, and spreadsheet modeling for a project budget. Not tied to any other pathway.",
      entry: [],
      courses: ["real-world-math"],
    },
  },

  // Courses: prerequisites are HARD (locked). suggested_prereqs are soft
  // hints matching the whiteboard arrows but not binding on students.
  courses: [
    // ============ FRESHMAN ROW ============
    {
      slug: "computer-skills",
      title: "Computer Skills",
      pathway: "cs",
      site: "either",
      grade: [9],
      yearLong: true,
      credit: { cte: 1.0 },
      prerequisites: [],
      suggestedPrereqs: [],
      leadsTo: ["intro-to-cs", "industrial-design"],
      teachers: ["rm", "am"],
      status: "draft",
      source: "pptx-learning-targets",
      proficiencies: [
        "Demonstrates proficient touch typing at a target words-per-minute threshold",
        "Navigates a modern OS, manages files, and uses cloud storage and collaboration tools",
        "Produces documents, spreadsheets, and presentations with correct formatting and basic formulas",
        "Applies digital citizenship principles: privacy, copyright, and safe online communication",
        "Demonstrates introductory problem-solving with visual or block-based programming",
      ],
      description: `Computer Skills is the 9th-grade on-ramp for every student entering Applied Tech. It covers the practical computing fluency every pathway assumes: keyboarding, file management, productivity software, digital citizenship, and a first look at programming through visual tools. Students finish the year ready to step into any of the post-freshman pathways — from Intro to CS to Industrial Design — without being slowed down by tool basics.`,
    },
    {
      slug: "woods-1",
      title: "Woods 1",
      pathway: "woods",
      site: "either",
      grade: [9],
      yearLong: true,
      credit: { cte: 1.0 },
      prerequisites: [],
      suggestedPrereqs: [],
      leadsTo: ["woods-2", "carpentry", "intro-to-engineering", "architecture"],
      teachers: ["ak", "am", "sr"],
      status: "review",
      source: "filled-docx + pptx",
      proficiencies: [
        "Follows shop safety protocols and passes a machine-specific safety checkoff for hand and power tools",
        "Reads and produces a working drawing for a small woodworking project",
        "Performs fundamental joinery: butt, lap, rabbet, and dado",
        "Selects appropriate wood species and finish for a given project",
        "Completes a portfolio of hand-tool and machine-tool projects by end of year",
      ],
      description: `Woods 1 is the hands-on freshman entry to the shop. Students learn how to work safely in a wood shop, operate the core hand and machine tools, and complete a sequence of skill-building projects. By spring they move from square-and-plane exercises to small furniture or case pieces that demonstrate clean joinery and finish work. This course is the foundation for Woods II, Carpentry, and is also useful background for students heading into Engineering, Architecture, or Industrial Design.`,
    },
    {
      slug: "metals-1",
      title: "Metals 1",
      pathway: "metals",
      site: "either",
      grade: [9],
      yearLong: true,
      credit: { cte: 1.0 },
      prerequisites: [],
      suggestedPrereqs: [],
      leadsTo: ["metals-2", "autos-1", "vehicular-drone-design", "industrial-design"],
      teachers: ["am", "sr", "jj"],
      status: "review",
      source: "cvhs-handbook",
      proficiencies: [
        "Passes shop safety checkoff for basic metal-working tools, cutting, grinding, and PPE",
        "Reads and lays out a simple sheet-metal pattern and executes cuts to tolerance",
        "Performs foundational fabrication: layout, cutting, bending, drilling, and fastening",
        "Demonstrates introductory welding or joining processes under supervision",
        "Completes a sheet-metal or light-fabrication project with clean finish work",
      ],
      description: `Metals 1 introduces the materials, tools, and safety practices of a metals shop. Students learn layout and measurement, basic cutting and forming of sheet metal, fastening techniques, and get their first supervised exposure to welding and machining. The course is the freshman entry for both the Metals lane (continuing into Metals II at CHS) and the Automotive lane (where metal fabrication is a daily skill).`,
    },

    // ============ CS LADDER (CHS) ============
    {
      slug: "intro-to-cs",
      title: "Intro to Computer Science",
      pathway: "cs",
      site: "chs",
      grade: [10, 11, 12],
      yearLong: true,
      credit: { cte: 1.0 },
      prerequisites: [],
      suggestedPrereqs: ["computer-skills"],
      leadsTo: ["advanced-cs"],
      teachers: ["rm"],
      status: "draft",
      source: "pptx-learning-targets",
      proficiencies: [
        "Writes, tests, and debugs programs in a text-based language (Python or JavaScript)",
        "Uses variables, control flow, functions, and basic data structures (list, dict) correctly",
        "Decomposes a problem into sub-tasks and implements an iterative solution",
        "Reads and modifies code written by others; uses version control basics (git clone, commit, push)",
        "Completes a term project that solves a real-world problem with code",
      ],
      description: `Intro to Computer Science teaches the craft of programming. Students move from their first lines of code to writing programs hundreds of lines long, with a focus on breaking big problems into small ones, testing their work, and reading code written by other people. By spring each student ships a term project of their own design — a game, a tool, a small web page — using what they've learned. This is the prerequisite for Advanced CS.`,
    },
    {
      slug: "advanced-cs",
      title: "Advanced Computer Science",
      pathway: "cs",
      site: "chs",
      grade: [11, 12],
      yearLong: true,
      credit: { cte: 1.0 },
      prerequisites: [],
      suggestedPrereqs: ["intro-to-cs"],
      leadsTo: ["capstone-cs"],
      teachers: ["rm"],
      status: "draft",
      source: "pptx-learning-targets",
      proficiencies: [
        "Designs and implements programs using object-oriented or functional paradigms as appropriate",
        "Selects and analyzes appropriate data structures (lists, maps, trees, graphs) for a given problem",
        "Reasons about algorithm correctness and Big-O time/space complexity",
        "Collaborates on a multi-file codebase using git branches, pull requests, and code review",
        "Builds a substantial project (multi-week) with tests, documentation, and version history",
      ],
      description: `Advanced CS picks up where Intro leaves off. Students learn how professional software is organized: data structures, algorithms, and working in a codebase with other people. Collaboration is central — students review each other's code and merge contributions using git. Coursework balances classic CS concepts with modern practice, preparing students for Capstone CS and for college-level computer science.`,
    },
    {
      slug: "capstone-cs",
      title: "Capstone Computer Science",
      pathway: "cs",
      site: "chs",
      grade: [12],
      yearLong: true,
      credit: { cte: 1.0 },
      prerequisites: [],
      suggestedPrereqs: ["advanced-cs"],
      leadsTo: [],
      teachers: ["rm"],
      status: "draft",
      source: "pptx-learning-targets",
      proficiencies: [
        "Scopes and executes a year-long software project from proposal to shipped product",
        "Writes a design document that covers requirements, architecture, and testing strategy",
        "Demonstrates ability to research and adopt new libraries, APIs, or languages independently",
        "Presents work in a public showcase to peers, staff, and community stakeholders",
        "Maintains professional development practices: version control, tests, documentation, deploy",
      ],
      description: `Capstone CS is a year-long, self-directed project. Students propose a piece of software they'll build — a web app, a game, an automation tool, a research project — and take it all the way from idea to a working, documented, deployed product. The course emphasizes the skills that separate a student coder from a professional one: design before code, test as you go, communicate what you built, and ship. Students present their capstone in a public showcase.`,
    },

    // ============ ENGINEERING LANE (CVHS) ============
    {
      slug: "intro-to-engineering",
      title: "Intro to Engineering",
      pathway: "engineering",
      site: "cvhs",
      grade: [10, 11, 12],
      yearLong: true,
      credit: { cte: 1.0 },
      prerequisites: [],
      suggestedPrereqs: [],
      leadsTo: ["architecture", "industrial-design"],
      teachers: ["ak", "sr", "am"],
      status: "review",
      source: "filled-docx (IDEA-derived)",
      proficiencies: [
        "Applies the engineering design process across a multi-week project from brief to prototype",
        "Produces 2D technical drawings and 3D parametric models (SolidWorks)",
        "Uses a digital fabrication workflow: design → CAM → CNC router, 3D printer, or laser engraver",
        "Writes clear design documentation and presents design decisions to a peer audience",
        "Demonstrates shop-safety fundamentals sufficient to work independently on approved tasks",
      ],
      description: `Intro to Engineering is the CVHS entry point for the Engineering, Architecture, and Industrial Design lanes. Students learn the engineering design process by running it themselves — from identifying a need, through CAD modeling in SolidWorks, to fabricating a prototype on the CNC router, laser engraver, or 3D printer. The course builds the core design, CAD, and shop fluency that every advanced pathway assumes. Closely adapted from the proven IDEA framework.`,
    },
    {
      slug: "engineering-science",
      title: "Engineering Science",
      pathway: "engineering",
      site: "cvhs",
      grade: [11, 12],
      yearLong: true,
      credit: { cte: 0.5, science: 0.5 },
      prerequisites: [],
      suggestedPrereqs: [],
      leadsTo: [],
      teachers: ["ak", "jj"],
      status: "draft",
      source: "PST-derived",
      proficiencies: [
        "Applies Newtonian mechanics to design problems: forces, moments, simple machines, materials",
        "Measures and reports physical quantities with correct units, significant figures, and uncertainty",
        "Designs, runs, and documents an experiment to test a quantitative hypothesis",
        "Uses a spreadsheet or code to analyze experimental data and produce charts",
        "Connects engineering design decisions to underlying physical principles in a final report",
      ],
      description: `Engineering Science is the dual-credit (CTE + science) course in the Engineering lane. Students work through the physics and materials science that sit beneath good engineering decisions: forces and moments, energy and work, material strength, measurement and data. Every major concept is anchored to a design or test project, not just a textbook problem. Successful completion carries both CTE and science credit.`,
    },

    // ============ ARCHITECTURE (CVHS) ============
    {
      slug: "architecture",
      title: "Architecture",
      pathway: "architecture",
      site: "cvhs",
      grade: [10, 11, 12],
      yearLong: true,
      credit: { cte: 1.0 },
      prerequisites: [],
      suggestedPrereqs: [],
      leadsTo: [],
      teachers: ["ak", "sr"],
      status: "review",
      source: "cvhs-handbook + filled-docx",
      proficiencies: [
        "Produces floor plans, elevations, and sections to architectural drafting standards",
        "Builds a full Revit model of a residential structure with walls, roofs, openings, and schedules",
        "Designs a building to code-aware constraints (setbacks, egress, stair rise/run, accessibility)",
        "Integrates introductory Arduino electronics for a smart-building feature",
        "Presents a final design package: drawings, Revit model, physical model or renders, narrative",
      ],
      description: `Architecture at CVHS takes students from hand sketches to a complete Revit model of a residence. Coursework covers drafting conventions, building systems, code-aware design, and the craft of presenting a building idea clearly. Drawing on the Architecture & Microcontrollers heritage, students also integrate Arduino-based electronics for a smart-building feature. The year ends with a full design package suitable for a portfolio.`,
    },

    // ============ WOODS & CARPENTRY (CVHS) ============
    {
      slug: "woods-2",
      title: "Woods II",
      pathway: "woods",
      site: "cvhs",
      grade: [10, 11, 12],
      yearLong: true,
      credit: { cte: 1.0 },
      prerequisites: [],
      suggestedPrereqs: ["woods-1"],
      leadsTo: [],
      teachers: ["ak"],
      status: "review",
      source: "filled-docx + pptx",
      proficiencies: [
        "Executes advanced joinery: mortise and tenon, dovetail, and curved work",
        "Operates CNC router workflow from design to finished part",
        "Plans a multi-week furniture project with a cut list, material takeoff, and schedule",
        "Applies multiple finish systems (oil, lacquer, water-based) and justifies the choice",
        "Leads a shop area during class: setup, safety, cleanup, and mentoring Woods 1 students",
      ],
      description: `Woods II moves students from skill exercises into real furniture and case pieces. Coursework emphasizes planning — cut lists, material takeoffs, schedules — alongside advanced joinery (mortise and tenon, dovetail) and CNC integration. Students also take leadership roles in the shop, setting up and supervising their own zones. The course prepares students for Carpentry and for any pathway where independent shop work matters.`,
    },
    {
      slug: "carpentry",
      title: "Carpentry",
      pathway: "woods",
      site: "cvhs",
      grade: [11, 12],
      yearLong: true,
      credit: { cte: 1.0 },
      prerequisites: [],
      suggestedPrereqs: ["woods-1"],
      leadsTo: [],
      teachers: ["ak"],
      status: "review",
      source: "cvhs-handbook + filled-docx",
      proficiencies: [
        "Frames a wall, floor, and roof system to code, including headers and fire-blocking",
        "Reads residential plans and executes a material takeoff for a framing package",
        "Installs windows, doors, and exterior sheathing; flashes openings correctly",
        "Demonstrates jobsite safety including ladder, fall, and power-tool protocols",
        "Contributes a recorded workday to a community project (Unity Shelter or similar)",
      ],
      description: `Carpentry is a year-long, construction-focused course with a real build at its center. Students frame walls, floors, and roofs; install windows, doors, and sheathing; and practice the jobsite habits that separate finished work from rework. The course historically supports the Unity Shelter tiny-home project, giving students a recorded community work experience and a finished structure they helped build.`,
    },

    // ============ METALS (CHS advanced) ============
    {
      slug: "metals-2",
      title: "Metals II",
      pathway: "metals",
      site: "chs",
      grade: [10, 11, 12],
      yearLong: true,
      credit: { cte: 1.0 },
      prerequisites: [],
      suggestedPrereqs: ["metals-1"],
      leadsTo: ["metals-3", "vehicular-drone-design"],
      teachers: ["jj"],
      status: "review",
      source: "cvhs-handbook + pptx",
      proficiencies: [
        "Executes MIG, oxy-acetylene, and arc welds to a consistent visual and structural standard",
        "Performs precision machining operations: turning, milling, drilling to a drawing tolerance",
        "Reads a mechanical drawing with GD&T basics and produces a part to spec",
        "Selects appropriate metals and processes for a given application",
        "Completes an independent fabrication project with planning, execution, and documentation",
      ],
      description: `Metals II at CHS takes students into welding and precision machining. Coursework covers MIG, oxy-acetylene, and arc welding techniques; turning, milling, and drilling to tolerance; and reading mechanical drawings with GD&T basics. Students finish the year with an independent fabrication project they planned, built, and documented. The course is the prerequisite foundation for Metals III, for Vehicular/Drone Design, and for students heading into welding or machining careers.`,
    },
    {
      slug: "metals-3",
      title: "Metals III",
      pathway: "metals",
      site: "chs",
      grade: [11, 12],
      yearLong: true,
      credit: { cte: 1.0 },
      prerequisites: [],
      suggestedPrereqs: ["metals-2"],
      leadsTo: ["vehicular-drone-design"],
      teachers: ["jj"],
      status: "draft",
      source: "drafted — new course proposal, 2026-04 committee",
      proficiencies: [
        "Executes AWS SENSE Level 1 welds across SMAW, GMAW, and FCAW in multiple positions",
        "Performs TIG (GTAW) welds on thin-gauge carbon steel and aluminum",
        "Reads welding symbols and specifies the correct process for a given joint",
        "Inspects welds to AWS D1.1 visual criteria and performs destructive test coupons",
        "Plans, fabricates, and delivers a capstone project with a documented weld map and bill of materials",
      ],
      description: `Metals III is the advanced welding year at CHS, built on the foundation of Metals II. Students work toward AWS SENSE Level 1 across SMAW, GMAW, and FCAW processes and add TIG (GTAW) for thin-gauge steel and aluminum. Coursework covers reading welding symbols, specifying the correct process for each joint type, and inspecting welds to AWS D1.1 visual criteria — the same standards used on the jobsite. Each student finishes with a capstone fabrication they own from drawing through finished, documented part with a full weld map. This course closes the Metals pathway to a three-credit POS completer and is the natural bridge to Vehicular / Drone Design for students whose capstone build needs advanced metalwork.`,
    },

    // ============ MATH (CVHS) ============
    {
      slug: "real-world-math",
      title: "Real World Math",
      pathway: "math",
      site: "cvhs",
      grade: [10, 11, 12],
      yearLong: true,
      credit: { cte: 0.5, math: 0.5 },
      prerequisites: [],
      suggestedPrereqs: [],
      leadsTo: [],
      teachers: ["jj", "ak"],
      status: "draft",
      source: "drafted — no prior description",
      proficiencies: [
        "Applies measurement, fractions, and dimensional analysis to shop and construction problems",
        "Uses right-triangle trigonometry to solve layout and fabrication problems",
        "Estimates material quantities and costs for a project; produces a defensible budget",
        "Builds a spreadsheet model for a project (parts, labor, schedule) using formulas",
        "Presents a math-anchored project report connecting the numbers to real-world decisions",
      ],
      description: `Real World Math is the math-credit course in Applied Tech — aimed at students who learn best when math has a wrench in its hand. Content is anchored to shop, construction, and manufacturing problems: layout trig, material takeoffs, budgeting, spreadsheet modeling. Students who complete the course earn a math credit alongside CTE credit, giving them a second path through their math graduation requirement.`,
    },

    // ============ AUTOS LADDER (CHS) ============
    {
      slug: "autos-1",
      title: "Autos 1",
      pathway: "autos",
      site: "chs",
      grade: [10, 11, 12],
      yearLong: true,
      credit: { cte: 1.0 },
      prerequisites: [],
      suggestedPrereqs: [],
      leadsTo: ["autos-2"],
      teachers: ["jj"],
      status: "draft",
      source: "pptx-learning-targets",
      proficiencies: [
        "Performs routine service: oil change, tire rotation, brake and fluid inspection",
        "Identifies major vehicle systems (engine, drivetrain, brakes, electrical, HVAC) and their components",
        "Uses a scan tool to read and interpret OBD-II diagnostic trouble codes",
        "Works safely in an auto shop: lifts, jacks, PPE, hot work, battery handling",
        "Documents a service task with a written work order and customer-ready explanation",
      ],
      description: `Autos 1 is the entry to the three-year automotive sequence at CHS. Students learn how a car works, how to work on one safely, and how to perform the routine service that keeps a vehicle on the road. Coursework balances hands-on shop time with diagnostic fundamentals — including reading OBD-II codes with a scan tool — and with the job-shop habits (work orders, customer communication) that matter in the field.`,
    },
    {
      slug: "autos-2",
      title: "Autos 2",
      pathway: "autos",
      site: "chs",
      grade: [11, 12],
      yearLong: true,
      credit: { cte: 1.0 },
      prerequisites: [],
      suggestedPrereqs: ["autos-1"],
      leadsTo: ["autos-3"],
      teachers: ["jj"],
      status: "draft",
      source: "pptx-learning-targets",
      proficiencies: [
        "Diagnoses and repairs brake systems, including hydraulic and ABS fundamentals",
        "Services suspension and steering components; performs basic alignment checks",
        "Diagnoses electrical faults using a DMM and wiring diagrams",
        "Performs engine maintenance: timing components, cooling system, tune-ups",
        "Completes a multi-day repair job from work order through road-test and signoff",
      ],
      description: `Autos 2 deepens diagnosis and repair. Students move from routine service into systems-level work: brakes, suspension and steering, electrical troubleshooting, and engine maintenance. Each unit ends with a multi-day repair job the student owns end-to-end, from work order through road-test. By year end students can tackle the majority of jobs a general-service shop would see.`,
    },
    {
      slug: "autos-3",
      title: "Autos 3",
      pathway: "autos",
      site: "chs",
      grade: [12],
      yearLong: true,
      credit: { cte: 1.0 },
      prerequisites: [],
      suggestedPrereqs: ["autos-2"],
      leadsTo: [],
      teachers: ["jj"],
      status: "draft",
      source: "pptx-learning-targets",
      proficiencies: [
        "Diagnoses drivability issues using data: live sensor data, scan-tool freeze frames, waveforms",
        "Performs transmission and drivetrain service at an introductory level",
        "Applies HVAC service fundamentals including refrigerant handling (EPA 609 readiness)",
        "Leads a shop area: job assignment, quality control, and mentoring Autos 1/2 students",
        "Produces a capstone repair or restoration project with documentation and presentation",
      ],
      description: `Autos 3 is the capstone of the automotive ladder. Students take on diagnostic work that rewards data-driven thinking — live sensor reads, waveforms, drivability puzzles — and move into transmissions, drivetrains, and HVAC service (with a path toward EPA 609 readiness). Seniors also lead the shop: assigning work, inspecting quality, and coaching the year-below students. Each student finishes with a capstone repair or restoration project.`,
    },

    // ============ INDUSTRIAL DESIGN (CVHS) ============
    {
      slug: "industrial-design",
      title: "Industrial Design",
      pathway: "industrial-design",
      site: "cvhs",
      grade: [10, 11, 12],
      yearLong: true,
      credit: { cte: 1.0 },
      prerequisites: [],
      suggestedPrereqs: [],
      leadsTo: ["industrial-design-2"],
      teachers: ["rm", "am"],
      status: "review",
      source: "pptx-learning-targets + STEAM-adjacent",
      proficiencies: [
        "Applies a user-centered design process: research, sketch, prototype, test, iterate",
        "Produces presentation-quality sketches and renderings for a product concept",
        "Builds parametric 3D models in SolidWorks and generates manufacturing-ready drawings",
        "Fabricates functional prototypes using 3D printing, CNC, laser cutting, and hand tools",
        "Presents a design narrative: problem, users, concept, trade-offs, next steps",
      ],
      description: `Industrial Design is where ideas become physical products. Students run a user-centered design process — research, sketching, 3D modeling, prototyping, and testing — across multiple projects. Tools include SolidWorks, 3D printers, laser cutters, and the CNC router. The course builds the portfolio-ready skills a student needs for design school or a manufacturing career, and feeds directly into Industrial Design II.`,
    },
    {
      slug: "industrial-design-2",
      title: "Industrial Design II",
      pathway: "industrial-design",
      site: "cvhs",
      grade: [11, 12],
      yearLong: true,
      credit: { cte: 1.0 },
      prerequisites: [],
      suggestedPrereqs: ["industrial-design"],
      leadsTo: [],
      teachers: ["am"],
      status: "draft",
      source: "drafted — ID II has no prior description on file",
      proficiencies: [
        "Scopes and executes a self-directed design project from brief to finished product",
        "Produces a professional design portfolio suitable for post-secondary applications",
        "Uses advanced SolidWorks features: assemblies, configurations, surfacing, rendering",
        "Performs basic design-for-manufacture analysis: tolerances, materials, cost trade-offs",
        "Collaborates with a community or client partner on a real design brief",
      ],
      description: `Industrial Design II is the advanced, self-directed year. Students choose a project — a product, a piece of equipment, a redesign of something that frustrates them — and take it from brief through finished, documented work. The course leans on more advanced SolidWorks features, introduces design-for-manufacture thinking, and emphasizes portfolio production. Where possible, projects connect to a real client or community partner.`,
    },

    // ============ VEHICULAR / DRONE (CHS) ============
    {
      slug: "vehicular-drone-design",
      title: "Vehicular / Drone Design",
      pathway: "vehicular",
      site: "chs",
      grade: [11, 12],
      yearLong: true,
      credit: { cte: 1.0 },
      prerequisites: [],
      suggestedPrereqs: ["metals-1", "metals-2"],
      leadsTo: [],
      teachers: ["jj"],
      status: "draft",
      source: "pptx-learning-targets",
      proficiencies: [
        "Scopes a vehicle or drone project: mission, constraints, bill of materials, schedule",
        "Designs a chassis or airframe in CAD and fabricates it from metal or composite stock",
        "Integrates propulsion, power, and control systems (electric drive or small engine, RC or autonomous)",
        "Tests the build safely: static checks, low-speed shakedown, progressive envelope expansion",
        "Documents the project in a build log and presents results with flight or run data",
      ],
      description: `Vehicular / Drone Design is a capstone-style course where students design, build, and test a vehicle or drone from scratch. The course pulls together metals fabrication, electronics, CAD, and project management — students run it like a small engineering shop. Every project carries a build log, and the year ends with a run or flight test that produces real data about how the design performed.`,
    },
  ],

  // ============ CAREERS ============
  // Career destinations the Applied Tech curriculum points toward. Each
  // career lists the Applied Tech courses that prepare a student for it —
  // must-have (core to the career) and supporting (useful, not required).
  // Post-HS options and wage guidance are directional, drawn from US BLS
  // Occupational Outlook Handbook, O*NET, and LBCC's 2025 catalog.
  // Every career carries a "source" field naming the data vintage. Numbers
  // drift; a counselor should be the source of truth for any specific
  // student conversation.
  careers: [
    {
      slug: "welder",
      title: "Welder / Fabricator",
      domain: "trades",
      one_liner: "Join and fabricate metal for construction, manufacturing, and repair shops.",
      must_have: ["metals-1", "metals-2", "metals-3"],
      supporting: ["real-world-math", "vehicular-drone-design", "intro-to-engineering"],
      certs: ["AWS SENSE Level 1 (SMAW/GMAW/FCAW)", "OSHA-10 General Industry", "TIG competency (via Metals III)"],
      post_hs: [
        { name: "LBCC Welding Technology AAS", type: "community-college" },
        { name: "Ironworkers Local 29 / Pipefitters Local 290 apprenticeship", type: "apprenticeship" },
        { name: "Entry-level welder at a fabrication shop", type: "direct-hire" },
      ],
      typical_wage_entry: "$22–28 / hr in Oregon (BLS May 2024)",
      outlook: "Steady demand in Oregon through 2032; infrastructure, shipyards, and fabrication shops are the dominant employers.",
      description: `Welders join metal parts using heat and electricity. The work is hands-on, code-regulated, and pays well for someone willing to put in time at the torch. Welders work in structural construction (buildings, bridges), pipe (process plants, utilities), fabrication shops (trailers, equipment), and shipyards. Entry-level welders typically start on simpler MIG or stick work and earn certifications in more processes over time.\n\nOur Metals 1 → II → III sequence at CHS takes a student to AWS SENSE Level 1 competency across SMAW, GMAW, and FCAW with TIG added in Metals III — the direct technical baseline a welding shop or LBCC's program is looking for. Pair it with Real World Math for the estimating and layout math that separates a clean welder from a fast one.`,
      source: "BLS OOH: Welders, Cutters, Solderers, and Brazers · O*NET 51-4121 · LBCC WLD program catalog (2024–25)",
    },
    {
      slug: "auto-technician",
      title: "Auto Technician",
      domain: "trades",
      one_liner: "Diagnose and repair cars and light trucks in dealerships, independent shops, or fleet garages.",
      must_have: ["metals-1", "autos-1", "autos-2", "autos-3"],
      supporting: ["real-world-math", "intro-to-engineering"],
      certs: ["ASE Entry-Level Student Certification", "EPA 609 (MVAC refrigerant handling)"],
      post_hs: [
        { name: "LBCC Automotive Technology AAS", type: "community-college" },
        { name: "Manufacturer apprenticeship (Toyota T-TEN, Honda PACT, Ford FACT)", type: "apprenticeship" },
        { name: "Entry-level lube tech → general service technician", type: "direct-hire" },
      ],
      typical_wage_entry: "$20–26 / hr in Oregon, often flat-rate after certification (BLS May 2024)",
      outlook: "Steady through 2032. EV and hybrid service is the fastest-growing specialization; traditional ICE work remains the volume employer.",
      description: `Auto techs diagnose what's wrong with a vehicle, then fix it. Modern auto work is as much about reading scan-tool data and wiring diagrams as it is about turning wrenches. The trade rewards diagnostic thinking, patience, and a willingness to keep learning — cars change every year.\n\nAt CHS, Autos 1 → 2 → 3 is the full three-year sequence under JJ Keim. Autos 1 teaches routine service and how a car works; Autos 2 moves into brakes, suspension, electrical, and engine work; Autos 3 is data-driven diagnostics plus an introduction to transmissions, drivetrain, and HVAC. Metals 1 is the freshman on-ramp (fabrication is a daily auto-shop skill). Real World Math covers the estimating and flat-rate math that matters once you're earning on a book-time system.`,
      source: "BLS OOH: Automotive Service Technicians and Mechanics · O*NET 49-3023.00 · LBCC AUT program catalog",
    },
    {
      slug: "carpenter",
      title: "Carpenter / Construction",
      domain: "trades",
      one_liner: "Build structures and finish interiors from framing lumber to cabinetry.",
      must_have: ["woods-1", "woods-2", "carpentry"],
      supporting: ["real-world-math", "architecture", "intro-to-engineering"],
      certs: ["NCCER Carpentry Level 1", "OSHA-10 Construction", "Documented jobsite hours (via Carpentry's community-build partnership)"],
      post_hs: [
        { name: "Pacific Northwest Carpenters Apprenticeship (PNWC)", type: "apprenticeship" },
        { name: "LBCC Construction Technology", type: "community-college" },
        { name: "Residential framing or finish crew", type: "direct-hire" },
      ],
      typical_wage_entry: "$19–25 / hr in Oregon; journey-level carpenters earn $35+ (BLS May 2024)",
      outlook: "Strong through 2032 — Oregon housing demand and an aging workforce make this one of the most in-demand trades in the region.",
      description: `Carpenters build things. Residential framers put up houses; commercial carpenters build schools and offices; finish carpenters do cabinetry, trim, and stairs. The trade is physical, outdoor (mostly), and pays an honest wage that rises quickly with experience. Carpentry-focused students often land in an apprenticeship straight out of high school.\n\nOur Woods 1 → Woods II → Carpentry sequence at CVHS runs a student from hand-tool basics through furniture-grade joinery to real construction — including the Unity Shelter tiny-home build, which generates documentable jobsite hours. Architecture is the supporting course that teaches plan-reading; Real World Math is the course that teaches cost estimating and material takeoffs. Adam Kirsch runs the wood shop and the construction side.`,
      source: "BLS OOH: Carpenters · O*NET 47-2031.00 · PNWC apprenticeship page · LBCC Construction Tech catalog",
    },
    {
      slug: "machinist",
      title: "Machinist / CNC Operator",
      domain: "trades",
      one_liner: "Make precision metal and plastic parts on manual and CNC machine tools.",
      must_have: ["metals-1", "metals-2", "industrial-design"],
      supporting: ["intro-to-engineering", "industrial-design-2", "real-world-math"],
      certs: ["NIMS basic credentials (machining Level 1)", "CSWA (SolidWorks Associate)", "GD&T module (via Metals II)"],
      post_hs: [
        { name: "LBCC Machine Tool Technology AAS", type: "community-college" },
        { name: "Manufacturing apprenticeship (Associated General Contractors, local shops)", type: "apprenticeship" },
        { name: "Entry-level CNC operator at a precision shop", type: "direct-hire" },
      ],
      typical_wage_entry: "$20–26 / hr in Oregon; programming-capable machinists earn $30+ (BLS May 2024)",
      outlook: "Growing, with aerospace and medical-device manufacturing driving demand for precision machinists in the Willamette Valley.",
      description: `Machinists cut material to precise shapes on lathes, mills, and CNC machines. The job rewards spatial thinking, careful setup, and the patience to debug a part until it's within tolerance. Modern machining is increasingly CNC-first — programming the machine is as important as running it.\n\nMetals II (CHS, JJ Keim) teaches the machining fundamentals — turning, milling, drilling to tolerance, reading mechanical drawings with GD&T. Industrial Design I (CVHS, McAteer / Macdonald) teaches the CAD-to-CAM workflow that bridges design to CNC. The combination of the two is unusually powerful for a high-school student heading into machining — LBCC's Machine Tool program assumes both.`,
      source: "BLS OOH: Machinists and Tool and Die Makers · O*NET 51-4041.00 · LBCC MT program catalog",
    },
    {
      slug: "software-developer",
      title: "Software Developer",
      domain: "computing",
      one_liner: "Build software — web, mobile, games, tools — at companies or as a solo developer.",
      must_have: ["computer-skills", "intro-to-cs", "advanced-cs", "capstone-cs"],
      supporting: ["industrial-design", "intro-to-engineering"],
      certs: ["AP Computer Science Principles eligibility", "Portfolio on GitHub (via Capstone CS)"],
      post_hs: [
        { name: "4-year CS degree (OSU, U of O, PSU, out-of-state)", type: "four-year" },
        { name: "LBCC Computer Systems AAS → transfer", type: "community-college" },
        { name: "Bootcamp (Thinkful, Springboard, etc.) → junior developer", type: "bootcamp" },
        { name: "Direct hire into support / QA / junior dev roles", type: "direct-hire" },
      ],
      typical_wage_entry: "$65–85k starting for new college graduates in Oregon (BLS May 2024)",
      outlook: "Faster-than-average growth through 2032, with particular demand for developers who can work across web, data, and ML.",
      description: `Software developers design, write, test, and maintain code. The field spans web (front-end, back-end, full-stack), mobile (iOS, Android), data (analytics, ML), games, embedded systems, and tools. What all specializations share is a habit of breaking a problem into sub-problems and shipping working code under uncertainty.\n\nRandy Macdonald's CS ladder at CHS — Intro CS → Advanced CS → Capstone CS — is a three-year sequence where each course builds directly on the previous. Capstone CS is a self-directed year-long project a student can show to a college admissions office, a recruiter, or a bootcamp. Computer Skills in 9th grade is recommended on-ramp; students who already program can skip it. Industrial Design I is the supporting course for students interested in the product side of software.`,
      source: "BLS OOH: Software Developers, Quality Assurance Analysts, and Testers · O*NET 15-1252.00 · College Scorecard",
    },
    {
      slug: "engineer",
      title: "Engineer (any discipline)",
      domain: "engineering",
      one_liner: "Design things that work — machines, buildings, circuits, processes — to real-world constraints.",
      must_have: ["woods-1", "intro-to-engineering", "engineering-science"],
      supporting: ["metals-1", "industrial-design", "industrial-design-2", "architecture", "real-world-math"],
      certs: ["CSWA (SolidWorks Associate) via Intro to Engineering", "Dual-credit Science (via Engineering Science)"],
      post_hs: [
        { name: "4-year engineering degree (OSU, U of O, PSU, out-of-state — ABET accredited)", type: "four-year" },
        { name: "LBCC Engineering Transfer AS (AAOT) → 4-year transfer", type: "community-college" },
      ],
      typical_wage_entry: "$70–90k starting for new ABET-accredited graduates in Oregon (BLS May 2024)",
      outlook: "Consistent long-term demand; Oregon engineering employers include Intel, Boeing, NW Natural, and the state DOT.",
      description: `Engineering is the practice of using math, science, and materials to design solutions to real-world problems. Mechanical engineers design machines; civil and structural engineers design buildings and bridges; electrical engineers design circuits and systems; chemical engineers design processes. What they share is the design process — understand the problem, propose a solution, model it, prototype it, test it, iterate.\n\nAdam Kirsch's Intro to Engineering at CVHS is our students' entry into that design process. It's CAD-heavy (SolidWorks, CSWA-ready) and project-structured. Engineering Science (CVHS, dual-credit science) pairs the design work with the physics that underpins it — forces, materials, measurement. Industrial Design I / II deepen the CAD and manufacturing side. A student aiming at a 4-year engineering program should take both the engineering and the ID courses — they stack well.`,
      source: "BLS OOH: Engineers (all subcategories) · O*NET 17-21xx family · Oregon ABET-accredited programs",
    },
    {
      slug: "industrial-designer",
      title: "Industrial / Product Designer",
      domain: "design",
      one_liner: "Design the products people use — from furniture to consumer electronics to equipment.",
      must_have: ["industrial-design", "industrial-design-2"],
      supporting: ["woods-1", "metals-1", "intro-to-engineering", "architecture"],
      certs: ["CSWA → CSWP (SolidWorks Professional)", "Portfolio (built during Industrial Design II)"],
      post_hs: [
        { name: "4-year BFA / BS in Industrial Design (Portland State, Art Center, U of Oregon PPPM-adjacent)", type: "four-year" },
        { name: "LBCC CADD (Computer-Aided Design and Drafting) AAS", type: "community-college" },
        { name: "In-house design role at a small manufacturer", type: "direct-hire" },
      ],
      typical_wage_entry: "$55–75k starting for industrial designers in Oregon; CADD roles start $22–28 / hr (BLS May 2024)",
      outlook: "Modest growth. Strong portfolios matter more than credentials — a student with a great ID II portfolio can compete with BFA graduates.",
      description: `Industrial designers make products. They sketch ideas, model them in CAD, prototype them with 3D printing and CNC work, test them with real users, and hand them off to manufacturing. The job blends art-school instincts (what looks good, what feels right) with engineering rigor (what will work, what can be made at scale).\n\nAndy McAteer's Industrial Design I → II at CVHS is the two-year sequence. ID I teaches the user-centered design process, SolidWorks, and prototyping across 3D print / CNC / laser. ID II is a self-directed portfolio year — the deliverable is a portfolio a design school will take seriously. Freshman Woods 1 or Metals 1 gives the hands-on foundation; Intro to Engineering adds the engineering-rigor side.`,
      source: "BLS OOH: Industrial Designers · O*NET 27-1021.00 · LBCC CADD program catalog",
    },
    {
      slug: "architect",
      title: "Architect",
      domain: "design",
      one_liner: "Design buildings — residential, commercial, institutional — from first sketches through construction documents.",
      must_have: ["woods-1", "architecture"],
      supporting: ["intro-to-engineering", "industrial-design", "real-world-math"],
      certs: ["Autodesk Certified User — Revit (via Architecture)", "Portfolio of drawings + Revit models"],
      post_hs: [
        { name: "5-year B.Arch or 4+2 M.Arch program (U of O, PSU, out-of-state NAAB-accredited)", type: "four-year" },
        { name: "Intern → licensed architect (NCARB, AXP, ARE) — 5 to 7 years post-degree", type: "licensure-track" },
      ],
      typical_wage_entry: "$55–70k starting for unlicensed interns / designers; $85k+ once licensed (BLS May 2024)",
      outlook: "Steady; Oregon architecture firms specialize in residential, timber / mass timber construction, and sustainable design.",
      description: `Architects design buildings. The work is a mix of creative problem-solving (what should this building be?) and technical craft (how does it actually get built, to code, on budget?). Licensure takes years — a student looking at architecture should expect a long runway. The reward is the privilege of making spaces people use every day.\n\nStephanie Reinwald and Adam Kirsch's Architecture course at CVHS takes a student from hand sketching to a full Revit model of a residence, with a pass through building code, structural basics, and integrated smart-building electronics. Woods 1 is the freshman on-ramp (every architect benefits from knowing how buildings go together). Industrial Design is the supporting course for students whose architecture interest leans toward furniture, fixtures, or interior design. Real World Math is useful for the cost-of-building conversations an architect ends up in.`,
      source: "BLS OOH: Architects, Except Landscape and Naval · O*NET 17-1011.00 · NAAB-accredited Oregon programs",
    },
    {
      slug: "drone-pilot",
      title: "Drone Pilot / UAV Operator",
      domain: "emerging",
      one_liner: "Operate unmanned aerial systems for mapping, inspection, photography, agriculture, or public safety.",
      must_have: ["metals-1", "vehicular-drone-design"],
      supporting: ["intro-to-engineering", "industrial-design", "advanced-cs"],
      certs: ["FAA Part 107 Remote Pilot Certificate (commercial UAS operations)", "Build log / flight-test portfolio"],
      post_hs: [
        { name: "Direct hire: surveying firm, inspection company, agricultural services, real-estate photography", type: "direct-hire" },
        { name: "LBCC Geomatics / Surveying or Engineering Transfer", type: "community-college" },
        { name: "4-year UAS or aviation program (OSU, Embry-Riddle, others)", type: "four-year" },
      ],
      typical_wage_entry: "$22–35 / hr for Part 107 commercial pilots; highly project-dependent (BLS does not break out UAS as its own category)",
      outlook: "Fast-growing. Agriculture, infrastructure inspection, and public safety are the three largest employment categories in Oregon.",
      description: `Drone pilots operate unmanned aircraft for a paying client — usually to collect images, video, sensor data, or to deliver a payload. The FAA Part 107 certification is the legal floor for commercial flight; it's a 60-question exam, and students can take it the week they turn 16. Specialization (mapping, inspection, cinematography, agriculture) is where the career actually lives.\n\nJJ Keim's Vehicular / Drone Design course at CHS is our students' entry into this field — it's a build-it-and-fly-it capstone where students design a vehicle or drone, fabricate it, and fly (or drive) it on a test course with instrumented results. Metals 1 is the freshman foundation; Advanced CS is the supporting course for students whose drone interest leans toward autonomy and flight programming.`,
      source: "FAA Part 107 Remote Pilot Certificate Guide · O*NET 53-2012.00 (related: commercial pilots) · AUVSI workforce report (2024)",
    },
    {
      slug: "trades-entrepreneur",
      title: "Skilled Trades Entrepreneur",
      domain: "trades",
      one_liner: "Run your own shop — welding, carpentry, auto repair, landscaping — as a small-business owner.",
      must_have: ["real-world-math"],
      supporting: ["metals-2", "metals-3", "carpentry", "autos-1", "autos-2", "autos-3", "woods-2", "industrial-design"],
      certs: ["Whatever trade certs go with the trade you choose (AWS, NCCER, ASE, etc.)", "Oregon Business Registration + CCB license for construction-adjacent trades"],
      post_hs: [
        { name: "Trade work first (5–10 years) → start your own shop", type: "direct-hire-then-business" },
        { name: "LBCC Small Business Management AAS (pairs with trade training)", type: "community-college" },
        { name: "Direct: subcontract under your trade license as an LLC or sole proprietor", type: "business" },
      ],
      typical_wage_entry: "Journey-level trade wages ($30–50+ / hr) → variable as an owner; successful single-truck operators commonly hit $100k+ gross",
      outlook: "Consistently in demand. Oregon has one of the highest rates of small-business ownership in trades nationally.",
      description: `The trades entrepreneur doesn't work for someone else — they work for themselves. A welder who runs a one-person mobile rig. A carpenter with a three-person finish crew. An auto tech who opened their own shop. The skill comes from the trade; the business comes from books, estimating, customer service, bidding, taxes, and knowing when to say no.\n\nThere is no single "owner pathway" in our curriculum — you pick a trade (welding, carpentry, auto, machining) and pair it with the business-flavored math. Real World Math is the only required course for this career path: the estimating, budgeting, and spreadsheet modeling it teaches are the mechanics of running a one-truck business. Everything else depends on which trade you want to own. Talk to your counselor and to Kirsch, Keim, or McAteer depending on the trade.`,
      source: "SBA small-business statistics · Oregon CCB licensing requirements · BLS self-employment data by occupation",
    },
    {
      slug: "construction-pm",
      title: "Construction Project Manager / Estimator",
      domain: "construction",
      one_liner: "Run construction jobs — budgets, schedules, crews — from first bid to final walkthrough.",
      must_have: ["carpentry", "real-world-math"],
      supporting: ["woods-2", "architecture", "intro-to-engineering"],
      certs: ["OSHA-10 Construction", "NCCER Carpentry Level 1", "CCB (Oregon Construction Contractors Board) licensing (post-HS)"],
      post_hs: [
        { name: "4-year Construction Management BS (OSU, boise State, others)", type: "four-year" },
        { name: "LBCC Construction Tech → transfer or field work", type: "community-college" },
        { name: "Crew lead → superintendent → PM track (field-first path, 5–10 years)", type: "direct-hire" },
      ],
      typical_wage_entry: "$55–75k for entry PMs with a 4-year degree; $45–55k for estimators; field-first PMs often start lower and bypass the degree (BLS May 2024)",
      outlook: "Strong growth. Oregon construction spending is rising; field-experienced PMs are scarce.",
      description: `Construction PMs turn a set of drawings and a budget into a finished building. The day is a mix of field coordination (is the framing crew on schedule?), money (are we on budget? what's the change-order impact?), and people (which subcontractor needs a conversation?). Estimators are the upstream version of this role — they turn drawings into the bid that wins the job.\n\nOur Carpentry course is the field foundation; Real World Math is the estimating, budgeting, and spreadsheet course — for a PM, it's arguably more important than the shop time. Architecture teaches you to read construction documents. Intro to Engineering is useful for understanding the engineering conversations you'll be in as a PM on a commercial job.`,
      source: "BLS OOH: Construction Managers · O*NET 11-9021.00 · Oregon CCB licensing requirements · AGC of America workforce data",
    },
  ],
};
